# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pverg\OneDrive\Escritorio\Temario Asignaturas\Grado de Datos\Ingeniería de Software (Grado de Datos)\Prácticas\PatroMVC\PatronMVC - Qt\src\vista\ui\Registro.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 450)
        MainWindow.setMinimumSize(QtCore.QSize(400, 450))
        MainWindow.setMaximumSize(QtCore.QSize(400, 450))
        MainWindow.setStyleSheet("#MainWindow {\n"
" background: qlineargradient(spread:pad, x1:0.498, y1:0.9265, x2:0.482587, y2:0.119, stop:0 rgb(170, 170, 170), stop:1 rgb(240, 240, 240));\n"
"}\n"
"\n"
"/* Entradas de texto */\n"
"QLineEdit {\n"
"    background-color: #ffffff;\n"
"    border: 2px solid #c0c0c0;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"/* Texto */\n"
"QLabel {\n"
"    color: #000000;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Botón */\n"
"QPushButton {\n"
"    background-color: #4CAF50; /* Color de fondo */\n"
"    border: none;\n"
"    color: white;\n"
"    text-align: center;\n"
"    text-decoration: none;\n"
"    font-size: 14px;\n"
"    margin: 4px 2px;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"/*Botón está presionado */\n"
"QPushButton:pressed {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"/* Imagen */\n"
"QLabel#label_6 {\n"
"    border-image: url(:/src/vista/Imagenes/registro.png);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(45, 121, 91, 271))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(11, 11, 31, 442))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(150, 110, 211, 291))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.lineID = QtWidgets.QLineEdit(self.frame_3)
        self.lineID.setGeometry(QtCore.QRect(20, 30, 171, 31))
        self.lineID.setObjectName("lineID")
        self.lineNombre = QtWidgets.QLineEdit(self.frame_3)
        self.lineNombre.setGeometry(QtCore.QRect(20, 80, 171, 31))
        self.lineNombre.setObjectName("lineNombre")
        self.lineApellido1 = QtWidgets.QLineEdit(self.frame_3)
        self.lineApellido1.setGeometry(QtCore.QRect(20, 130, 171, 31))
        self.lineApellido1.setObjectName("lineApellido1")
        self.lineApellido2 = QtWidgets.QLineEdit(self.frame_3)
        self.lineApellido2.setGeometry(QtCore.QRect(20, 180, 171, 31))
        self.lineApellido2.setObjectName("lineApellido2")
        self.lineEmail = QtWidgets.QLineEdit(self.frame_3)
        self.lineEmail.setGeometry(QtCore.QRect(20, 230, 171, 31))
        self.lineEmail.setObjectName("lineEmail")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(370, 11, 31, 442))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        self.frame_5.setGeometry(QtCore.QRect(50, 400, 311, 41))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.enviarBoton = QtWidgets.QPushButton(self.frame_5)
        self.enviarBoton.setGeometry(QtCore.QRect(100, 0, 111, 41))
        self.enviarBoton.setObjectName("enviarBoton")
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(50, 10, 311, 91))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        self.label_6.setGeometry(QtCore.QRect(60, 0, 181, 91))
        self.label_6.setStyleSheet("border-image: url(src/vista/Imagenes/registro.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Id Único"))
        self.label.setText(_translate("MainWindow", "Nombre"))
        self.label_2.setText(_translate("MainWindow", "1º Apellido"))
        self.label_3.setText(_translate("MainWindow", "2º Apellido"))
        self.label_5.setText(_translate("MainWindow", "Email"))
        self.enviarBoton.setText(_translate("MainWindow", "Enviar"))
import imagenes_rc
